### ISSUE TITLE
Global variables as JSON

### ISSUE THREAD

**Issue by mrjjwright** [pixelandtonic/ElementAPI#13]
Is there an easy way to get the global variables that are normally available to templates returned as JSON?  I know I can figure this out myself but I thought I would ask first.  

https://craftcms.com/docs/templating/global-variables

**Comment by brandonkelly** [comment]
@mrjjwright Yes, possible. Just posted a similar question on [craftcms.stackexchange.com](http://craftcms.stackexchange.com/) and answered it there: http://craftcms.stackexchange.com/a/14691/9

FFR please post usage questions on that site, and only post actual issues here, thanks!
