### ISSUE TITLE
Error when using parameter 'first' => true,

### ISSUE THREAD

**Issue by markresponsive** [pixelandtonic/ElementAPI#15]
Have been receiving this error when attempting to set a limit to results:
`Argument 2 passed to League\Fractal\Serializer\ArraySerializer::item() must be of the type array, object given, called in /var/www/Sites/craft-records/craft/plugins/elementapi/vendor/league/fractal/src/Scope.php on line 286 and defined `

It works if I set the object to an array, although the JSON does not return the key "data"
`$result = (array) $result;`

**Comment by takobell** [comment]
Can you share your `elementapi.php` file?

**Comment by markresponsive** [comment]
Hi,

Referring to endpoints elementapi.php
list/<slug:{slug}>.json
list/<handle:{handle}>/<slug:{slug}>.json
I am using two classes ListTransformer and DetailTransformer
The purpose of the two different classes is that I may be able to select collection versus single instance results. Its still in its infancy though but has a good road map.
These two classes extend FieldTransformer

When I was referring to data through the ListTransformer I was receiving paginated meta keys as well and no errors. 
Then using the DetailTransformer class I was using 'first' => true, and errors were resulting.
I was printing the objects that were being returned in  ListTransformer and DetailTransformer prior to being converted to JSON and structurally they were exactly the same except when passing to Fractal it chokes.

 [config.zip](https://github.com/pixelandtonic/ElementAPI/files/271364/config.zip)

**Comment by takobell** [comment]
Ahh, looks like that's going to be pretty difficult to try and replicate locally.  If you enable devMode, do you get a full stack trace with the error?  Might give some insight into where it's coming from (3rd party plugin related, etc.).  Also, if you've got xDebug installed, probably worth setting some strategic breakpoints in ElementApiController and stepping through to see what's happening.

**Comment by markresponsive** [comment]
Ok rabbit hole incident expecting an array and was passing an object, confusion was with the collections being objects within an array.
Thanks
