### ISSUE TITLE
Breaks with nested arrays in GET

### ISSUE THREAD

**Issue by timkelty** [pixelandtonic/ElementAPI#16]
Since #6, there is now a "Array to string conversion" notice if you try and pass an array in the GET.
E.g. `?criteria[section]=foo`

It looks like `UrlHelper`/`getUrl`/`_normalizeParams` doesn't play nice with nested arrays.

**Comment by takobell** [comment]
Can you make sure you're on the latest version of Craft, take the attached file, drop it in `craft/app/helpers` and let me know if it solves your problem and/or creates any unintended side-effects?

[UrlHelper.php.zip](https://github.com/pixelandtonic/ElementAPI/files/278799/UrlHelper.php.zip)

**Comment by timkelty** [comment]
Works like a charm! Hooray for `http_build_query`!

**Comment by takobell** [comment]
Cool... fix will be in the next Craft release.
