### ISSUE TITLE
Any suggestions on how to authenticate API calls?

### ISSUE THREAD

**Issue by ads1018** [pixelandtonic/ElementAPI#18]
I wrote a client side nodeJS app with a craftCMS backend using the ElementAPI for my REST endpoints. Is it possible to authenticate requests from a separate server? Ideally, I'd be able to send a session token along with my requests.

**Comment by AugustMiller** [comment]
Sounds like the standard Craft Controller/Service architecture is what you need— the ElementAPI wasn't designed for mutating data (although it certainly _can_ be used this way).

https://craftcms.com/docs/plugins/controllers

Standard Controller methods include ways of rejecting requests that don't meet certain criteria (i.e. Ajax, Anonymous, etc.)…

**Comment by davorpeic** [comment]
@ads1018 Hi, did you managed to get auth working with element api?
