### ISSUE TITLE
If you use a RichText Fieldtype, json returns empty string

### ISSUE THREAD

**Issue by owldesign** [pixelandtonic/ElementAPI#2]
Looks like an empty string is returned if Rich Text field is used. In the "news" example, variable body is also returning an empty string. Using Plain Text with line breaks works.

**Comment by owldesign** [comment]
Ok, so I might of answered my own issue. You just need to getRawContent() on the Rich Text field. See example bellow.

    'news/<entryId:\d+>.json' => function($entryId) {
            return [
                'elementType' => 'Entry',
                'criteria' => ['id' => $entryId],
                'first' => true,
                'transformer' => function(EntryModel $entry) {
                    $body       = $entry->body->getRawContent();
                    $summary    = $entry->summary->getRawContent();
                    return [
                        'title' => $entry->title,
                        'url' => $entry->url,
                        'summary' => $summary,
                        'body' => $body,
                    ];
                },
            ];
        },

If this is expected process we can close this ticket.

**Comment by brandonkelly** [comment]
Yep, that’s how you do it.

**Comment by jameswragg** [comment]
I'm in the same boat but finding getRawContent() doesn't render the image tags, e.g.
```
"summary": "<p><img src=\"{asset:46:url}\" alt=\"nobility-na.png#asset:46\" /><br /></p><p>Here youll find the summary text with an image.</p>"
```
How can I get ElementAPI to render full img tags in the returned HTML?

**Comment by pimkaptein** [comment]
I have the same issue as the user above! Would love to have this answered...

**Comment by rhinedesign** [comment]
use getParsedContent() instead of getRawContent() to return the rendered image tags
