### ISSUE TITLE
Best way to split elementary.php

### ISSUE THREAD

**Issue by eikebartels** [pixelandtonic/ElementAPI#20]
My file gets longer and longer for all the different endpoints I have. 

Is there a elegant way to split this. i.e.. For each endpoint a new file for even using the ElementAPI somehow inside a template?

**Comment by timkelty** [comment]
@eikebartels you can write your own transformer classes and keep them out of `config/elementapi.php`

Furthermore, I route everything through a `custom` plugin and build project-specific transformers.
Like so: https://gist.github.com/timkelty/8de8531df688b6ac08d2da0713b6ff00
