### ISSUE TITLE
Removing header

### ISSUE THREAD

**Issue by eikebartels** [pixelandtonic/ElementAPI#23]
Hey, 

I'm trying to remove some headers.  

```
'api/looks' => function () {
            HeaderHelper::setHeader([
                'Cache-Control' => 'that works'
            ]);
            HeaderHelper::removeHeader("Cache-Control");
            HeaderHelper::removeHeader("Pragma");
            return Custom_ElementApiHelper::getParams([
                'criteria' => ['section' => 'looks'],
                'transformer' => 'looks'
            ]);
        },
```

But it does not work. Any idea?

**Comment by timkelty** [comment]
@eikebartels this is probably best fielded here: http://craftcms.stackexchange.com/

I think you'll find this is related to default php session behavior, and not anything to do with this plugin. Read the answer thread here: http://craftcms.stackexchange.com/questions/2598/why-does-craft-set-no-cache-headers-for-all-requests/2600#2600

**Comment by eikebartels** [comment]
Alright thanks @timkelty

**Comment by eikebartels** [comment]
Stack could not really help me but I found a solution 

Is a bit quick and dirty for now but I like to share it for others. 

I the file `ElementApiController.php` you can modify the header i.e. 

```
HeaderHelper::removeHeader("Cache-Control");
HeaderHelper::removeHeader("Pragma");
$date = new DateTime('+1 day');
HeaderHelper::setHeader(["Expires" => $date->format('D, d M Y H:i:s \G\M\T')]);

```

this needs be be set right before 

```
craft()->elementApi->onBeforeSendData(new Event($this, [
			'data' => $data,
		]));
```
