### ISSUE TITLE
Missing CORS Header 

### ISSUE THREAD

**Issue by hauptbenutzer** [pixelandtonic/ElementAPI#4]
Maybe I'm missing some global settings here, but it seems there is no way to set proper CORS headers for the JSON response. 

If that's really just an oversight I'd be willing to contribute the necessary PR.

**Comment by brandonkelly** [comment]
You can do that by setting your endpoint config to an anonymous function:

```php
'my/endpoint/pattern' => function() {
    HeaderHelper::setHeader([
        'Access-Control-Allow-Origin' => 'http://example.com'
    ]);

    return [
        // ...
    ];
}
```

**Comment by hauptbenutzer** [comment]
Wow, that was quick, thanks! It seems like it would be a common use case, though. Maybe it can go into one of the examples?

**Comment by spotd** [comment]
This is now - Craft::$app->response->headers->set('Access-Control-Allow-Origin', 'http://domain.com');
How can we set multiple domains for development?

**Comment by brandonkelly** [comment]
@spotd I’m no CORS expert, but know you can whitelist _all_ domains by doing this: (Craft 3 code)

```Craft::$app->getResponse()->getHeaders()->set('Access-Control-Allow-Origin', '*');```

**Comment by spotd** [comment]
Great thanks
