### ISSUE TITLE
Is there a way to set the criteria based on a custom field?

### ISSUE THREAD

**Issue by sandy-abrightmind** [pixelandtonic/ElementAPI#8]
Is there any way to set the criteria based on a custom field?

Channel: Offers
Custom Field: Users

Can I query based on the Users which is a field that I added to my channel of "Offers"?

**Comment by timkelty** [comment]
users is a "Users" field? Do you want it do match ANY offers which have users?

**Comment by sandy-abrightmind** [comment]
Yeah, basically, I have a channel of Offers. And each offer can be assigned to multiple users.

Then I want to query by “user” all the offers that it has. Is that possible with the plugin?

Thanks,
Sandy Davis
--------------------------------------------------------------
Sandra Davis
A Bright Mind, Inc.
Biloxi, MS

**Comment by sandy-abrightmind** [comment]
And Yes, I’m using a “Users” field type for the custom field Users.

--------------------------------------------------------------
Sandra Davis
A Bright Mind, Inc.
Biloxi, MS

**Comment by timkelty** [comment]
In that case, something like this should work: 
```
<?php
namespace Craft;

return [
    'endpoints' => [
        'users/<userId:\d+>/offers.json' => function($userId) {
            return [
                'elementType' => 'Entry',
                'criteria' => [
                  'section' => 'offers'
                  'relatedTo' => $userId
                ],
                'transformer' => function(EntryModel $entry) {
                    return [
                        'title' => $entry->title,
                        'url' => $entry->url,
                        'summary' => $entry->summary,
                        'body' => $entry->body,
                    ];
                },
            ];
        },
    ]
];
```
Your endpoint would be /users/[userID]/services.json

**Comment by sandy-abrightmind** [comment]
It’s not returning any data. =(


--------------------------------------------------------------
Sandra Davis
A Bright Mind, Inc.
Biloxi, MS

**Comment by timkelty** [comment]
Try it again, I was missing a comma.
Also, try turning on `devMode`, it would catch errors like that.

**Comment by sandy-abrightmind** [comment]
No I mean the JSON has no data. It's not finding any related content. Even though, there are entries that have the user name "test".

I even changed it to look it up based on the username handle for the "related to" and endpoint configuration & that didn't work either.

I'm not sure what it's not finding the entries. :(

Get Outlook for mobile<https://aka.ms/b4fz91>

_____________________________

**Comment by brandonkelly** [comment]
Usage questions should be posted on http://craftcms.stackexchange.com (tagged with `plugin-elementapi`). This is not actually an issue with the plugin.

**Comment by sandy-abrightmind** [comment]
Sorry. I saw a label for questions so I thought I could post the question on the project page. I’ll post it on the stack exchange link below.

Thank you!
--------------------------------------------------------------
Sandra Davis
A Bright Mind, Inc.
Biloxi, MS
