### ISSUE TITLE
Query string not preserved for prev / next links

### ISSUE THREAD

**Issue by carlcs** [pixelandtonic/ElementAPI#9]
My endpoint is set up to return entries conditional on params of my query string, e.g., example.com/api/entries?lat=48.772789&lng=9.154120.

This query string is not preserved for the generated pagination links in the "meta" section. Is there anything I can do to make it preserve the info? Thanks

```json
{"next": "http:\/\/example.com\/api\/entries?page=2"}
```

**Comment by takobell** [comment]
https://github.com/pixelandtonic/ElementAPI/releases/tag/1.2.1
